version: '3.7'

services:

  nginx:
    image: nginx:1.23.0
    restart: always
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx:/etc/nginx/conf.d:ro
      - ./log:/var/log/nginx
      - ./generated:/var/www
    depends_on:
      - api
    ports:
      - "80:80"

  api:
    container_name: api
    image: api_image
    env_file:
      - ./docker/app-variables.env
    build: ./api
    depends_on:
      - redis
      - postgres
    volumes:
      - ./generated:/generated
    ports:
      - "8000:8000"

  postgres:
    container_name: postgres
    hostname: postgres
    image: library/postgres:14.1
    env_file:
      - ./docker/app-variables.env
    ports:
        - "5432:5432"

  redis:
    image: redis:6.2-alpine
    hostname: redis
    container_name: redis
    command:
      - 'redis-server'
    ports:
      - "6379:6379"

